// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwxSZevJA4mdVIrWR88rusuGdK9igObZ0',
    appId: '1:529958472761:web:9965e4b2a7fdbd13bb51e8',
    messagingSenderId: '529958472761',
    projectId: 'shopease-20c5e',
    authDomain: 'shopease-20c5e.firebaseapp.com',
    storageBucket: 'shopease-20c5e.firebasestorage.app',
    measurementId: 'G-HC327XDNPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRt-b9Ao1q6GcSM2XkiTeM-3lVakiuPuI',
    appId: '1:529958472761:android:d6078cb6458ad867bb51e8',
    messagingSenderId: '529958472761',
    projectId: 'shopease-20c5e',
    storageBucket: 'shopease-20c5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT9vjb-x5RMVc2yCFKGZpC97Of6ljvCHI',
    appId: '1:529958472761:ios:c7337dabf8f8d64abb51e8',
    messagingSenderId: '529958472761',
    projectId: 'shopease-20c5e',
    storageBucket: 'shopease-20c5e.firebasestorage.app',
    iosBundleId: 'com.example.shopEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT9vjb-x5RMVc2yCFKGZpC97Of6ljvCHI',
    appId: '1:529958472761:ios:c7337dabf8f8d64abb51e8',
    messagingSenderId: '529958472761',
    projectId: 'shopease-20c5e',
    storageBucket: 'shopease-20c5e.firebasestorage.app',
    iosBundleId: 'com.example.shopEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwxSZevJA4mdVIrWR88rusuGdK9igObZ0',
    appId: '1:529958472761:web:8fc049eb266f6cd5bb51e8',
    messagingSenderId: '529958472761',
    projectId: 'shopease-20c5e',
    authDomain: 'shopease-20c5e.firebaseapp.com',
    storageBucket: 'shopease-20c5e.firebasestorage.app',
    measurementId: 'G-9RBRSGK4S2',
  );
}
